// <auto-generated />
using System;
using Hotel_AdminPanel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel_AdminPanel.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240924162810_AddCustomers")]
    partial class AddCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hotel_AdminPanel.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            City = "CityA",
                            Country = "CountryA",
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Phone = "123456789",
                            PostalCode = "12345"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St",
                            City = "CityB",
                            Country = "CountryB",
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Phone = "987654321",
                            PostalCode = "54321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St",
                            City = "CityC",
                            Country = "CountryC",
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Phone = "456789123",
                            PostalCode = "67890"
                        },
                        new
                        {
                            Id = 4,
                            Address = "159 Maple St",
                            City = "CityD",
                            Country = "CountryD",
                            Email = "bob.johnson@example.com",
                            FirstName = "Bob",
                            LastName = "Johnson",
                            Phone = "321654987",
                            PostalCode = "13579"
                        },
                        new
                        {
                            Id = 5,
                            Address = "753 Oak St",
                            City = "CityE",
                            Country = "CountryE",
                            Email = "charlie.brown@example.com",
                            FirstName = "Charlie",
                            LastName = "Brown",
                            Phone = "258369147",
                            PostalCode = "24680"
                        },
                        new
                        {
                            Id = 6,
                            Address = "951 Birch St",
                            City = "CityF",
                            Country = "CountryF",
                            Email = "david.wilson@example.com",
                            FirstName = "David",
                            LastName = "Wilson",
                            Phone = "963852741",
                            PostalCode = "36912"
                        },
                        new
                        {
                            Id = 7,
                            Address = "357 Cedar St",
                            City = "CityG",
                            Country = "CountryG",
                            Email = "eve.davis@example.com",
                            FirstName = "Eve",
                            LastName = "Davis",
                            Phone = "147258369",
                            PostalCode = "78901"
                        },
                        new
                        {
                            Id = 8,
                            Address = "864 Walnut St",
                            City = "CityH",
                            Country = "CountryH",
                            Email = "frank.garcia@example.com",
                            FirstName = "Frank",
                            LastName = "Garcia",
                            Phone = "753159486",
                            PostalCode = "85246"
                        },
                        new
                        {
                            Id = 9,
                            Address = "258 Spruce St",
                            City = "CityI",
                            Country = "CountryI",
                            Email = "grace.martinez@example.com",
                            FirstName = "Grace",
                            LastName = "Martinez",
                            Phone = "951753456",
                            PostalCode = "14789"
                        },
                        new
                        {
                            Id = 10,
                            Address = "159 Fir St",
                            City = "CityJ",
                            Country = "CountryJ",
                            Email = "hank.lopez@example.com",
                            FirstName = "Hank",
                            LastName = "Lopez",
                            Phone = "258147369",
                            PostalCode = "96374"
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MealPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Plan = "No Meal"
                        },
                        new
                        {
                            Id = 2,
                            Plan = "Breakfast"
                        },
                        new
                        {
                            Id = 3,
                            Plan = "Half Board"
                        },
                        new
                        {
                            Id = 4,
                            Plan = "Full Board"
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adults")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("Children")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("ReservationStatusId");

                    b.HasIndex("RoomId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.ReservationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RStatus = "Reserved"
                        },
                        new
                        {
                            Id = 2,
                            RStatus = "CheckedIn"
                        },
                        new
                        {
                            Id = 3,
                            RStatus = "Completed"
                        },
                        new
                        {
                            Id = 4,
                            RStatus = "Canceled"
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAdults")
                        .HasColumnType("int");

                    b.Property<int>("MaxChildren")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomStatusId");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 100m,
                            RoomNumber = "A101",
                            RoomStatusId = 1,
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 150m,
                            RoomNumber = "A102",
                            RoomStatusId = 1,
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 200m,
                            RoomNumber = "A103",
                            RoomStatusId = 1,
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 250m,
                            RoomNumber = "A104",
                            RoomStatusId = 1,
                            RoomTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 300m,
                            RoomNumber = "A105",
                            RoomStatusId = 1,
                            RoomTypeId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Image = "",
                            MaxAdults = 0,
                            MaxChildren = 0,
                            Price = 350m,
                            RoomNumber = "A106",
                            RoomStatusId = 1,
                            RoomTypeId = 6
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.RoomStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Occupied"
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Studio"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Suite"
                        },
                        new
                        {
                            Id = 5,
                            Type = "MiniSuite"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Presidential"
                        });
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.Reservation", b =>
                {
                    b.HasOne("Hotel_AdminPanel.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_AdminPanel.Models.MealPlan", "MealPlan")
                        .WithMany()
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_AdminPanel.Models.ReservationStatus", "ReservationStatus")
                        .WithMany()
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_AdminPanel.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("MealPlan");

                    b.Navigation("ReservationStatus");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Hotel_AdminPanel.Models.Room", b =>
                {
                    b.HasOne("Hotel_AdminPanel.Models.RoomStatus", "RoomStatus")
                        .WithMany()
                        .HasForeignKey("RoomStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_AdminPanel.Models.RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomStatus");

                    b.Navigation("RoomType");
                });
#pragma warning restore 612, 618
        }
    }
}
